/*$Workfile: stdstl.h$ : include file for standard system include files,
  or project specific include files that are used frequently, but
  are changed infrequently
  $Revision: 4$ $Date: 2007-07-10 17:48:10$
  $Author: Darko Kolakovic$

  stdstl.h, stdstl.cpp
    These files are used to build a precompiled header (PCH) file
    named .pch and a precompiled types file named StdAfx.obj.
    Files are generated by Microsoft Visual Studio
 */

#pragma once

#define WIN32_LEAN_AND_MEAN		// Exclude rarely-used stuff from Windows headers
#include <stdio.h>

#ifdef __cplusplus
  #include <string>     //std::string
  #include "KOStream.h" //std::_tcout
  #include <iomanip.h>  //std::endl
  #include "KTypedef.h" //Type definitions
  #include "KTChar.h"   //Unicode mapping layer
  #include "KTrace.h"   //debugging tools
  #include "KString.h"  //CString
  #include "KTestLog.h" //CTestLog
#endif //__cplusplus
// TODO: reference additional headers your program requires here
