/*$Workfile: stdstl.cpp$ : source file that includes just the standard includes
  .pch will be the pre-compiled header
  $Revision: 3$ $Date: 2007-05-24 16:49:25$
  $Author: Darko Kolakovic$

  stdstl.h, stdstl.cpp
    These files are used to build a precompiled header (PCH) file
    named .pch and a precompiled types file named stdstl.obj.
    Files are generated by Microsoft Visual Studio
 */

#include "stdstl.h"

// TODO: reference any additional headers you need in STDAFX.H
// and not in this file
