/*$Workfile: stdstl.h$ : include file for standard system include files,
  or project specific include files that are used frequently, but
  are changed infrequently
  $Revision: 5$ $Date: 2007-07-16 17:52:51$
  $Author: Darko Kolakovic$

  stdstl.h, stdstl.cpp
    These files are used to build a precompiled header (PCH) file
    named .pch and a precompiled types file named StdAfx.obj.
    Files are generated by Microsoft Visual Studio
 */

#pragma once

#define WIN32_LEAN_AND_MEAN // Exclude rarely-used stuff from Windows headers
#ifdef _UNICODE
  #ifndef UNICODE
    //To enable Unicode for some Microsoft Visual C/C++ header files,
    //the UNICODE definition is required
    #define UNICODE
  #endif
#endif

#include <stdio.h>

#ifdef __cplusplus
  #include <string>     //std::string
  #include "STL/KOStream.h" //std::_tcout
  #if _MSC_VER <= 1200
    #include <iomanip.h>  //std::endl
  #endif
#endif //__cplusplus

#include "KTypedef.h" //Type definitions
#include "KTChar.h"   //Unicode mapping layer
#include "KTrace.h"   //debugging tools
#include "KTestLog.h" //CTestLog
// TODO: reference additional headers your program requires here
