/*$Workfile: S:\_SrcPool\Cpp\Samples\_LibraryTest\Src\stdafx.cpp$ : source file that includes just the standard includes
  _LibraryTest.pch will be the pre-compiled header
  stdafx.obj will contain the pre-compiled type information
  $Revision: 1.1 $ $Date: 2003/01/31 03:05:28 $
  $Author: ddarko $

  StdAfx.h, StdAfx.cpp
    These files are used to build a precompiled header (PCH) file
    named _LibraryTest.pch and a precompiled types file named StdAfx.obj.
    Files are generated by Microsoft Visual Studio
 */

#include "stdafx.h"

// TODO: reference any additional headers you need in STDAFX.H
// and not in this file
