/*$Workfile: TestAboutDlg.h$: header file
  $Revision: 1$ $Date: 2006-09-27 22:52:55$
  $Author: Darko$
  
  Interface of the CAboutDlg class
  Copyright: CommonSoft Inc
  2003-08-25 Darko Kolakovic
 */

// Group=Samples

#pragma once

#ifndef __AFXWIN_H__
  #error include 'stdafx.h' before including this file for PCH
#endif

#include "Resource.h"   // main symbols

///////////////////////////////////////////////////////////////////////////////
//Plain 'About' dialog automatically generated by IDE.
//
//Note: uses Microsoft Fundation Library (MFC);
//      Microsoft Windows specific (Win).
class CAboutDlg : public CDialog
{
public:
  CAboutDlg();
  virtual ~CAboutDlg();

// Dialog Data
  enum { IDD = IDD_ABOUTBOX };

protected:
  virtual void DoDataExchange(CDataExchange* pDX);    // DDX/DDV support

// Implementation
protected:
  DECLARE_MESSAGE_MAP()
};

///////////////////////////////////////////////////////////////////////////////
/*****************************************************************************
 * $Log: 
 *  1    Biblioteka1.0         2006-09-27 22:52:55  Darko           
 * $
 *****************************************************************************/
