/*$Workfile: S:\_SrcPool\Cpp\Samples\Common\Src\Win\stdafx.cpp$: implementation file
  $Revision: 8$ $Date: 2005-03-12 17:18:25$
  $Author: Darko$

  Source file that includes just the standard header files.
  ProjectFilename.pch will be the pre-compiled header stdafx.obj will contain
  the pre-compiled type information
  
  stdafx.h, stdafx.cpp
    These files are used to build a precompiled header (PCH) file
    named ProjectFilename.pch and a precompiled types file named stdafx.obj.
    Files are generated by Microsoft Visual Studio
 */

// Group=Examples


#include "stdafx.h"

#if _MSC_VER //Microsoft Visual Studio C++
  #pragma comment(compiler)

  #ifdef _STLP_DEBUG
    #pragma message ("  STLport library (debug) is required.")
    #if _MSC_VER == 1310 //Visual C++ .Net 2003, 32-bit, version 7.1
      #pragma comment( lib, "STL/STLport/lib/stlport_vc71_stldebug.lib" )
    #endif
  #endif
  #include "KDbgMacr.h" //Dump compiler-specific predefined macros
#endif //_MSC_VER

CTestLog g_logTest;   //general test logger

// Note: reference any additional headers you need in stdafx.h
// and not in this file

/*****************************************************************************
 * $Log:
 *  1    Biblioteka1.0         03/06/2004 2:29:39 PMDarko
 * $
 *****************************************************************************/
