/*$Workfile: stdafx.cpp$: implementation file
  $Revision: 7$ $Date: 2004-09-30 14:47:58$
  $Author: Darko$

  Source file that includes just the standard header files.
  ProjectFilename.pch will be the pre-compiled header stdafx.obj will contain
  the pre-compiled type information
  
  stdafx.h, stdafx.cpp
    These files are used to build a precompiled header (PCH) file
    named _LibraryTest.pch and a precompiled types file named stdafx.obj.
    Files are generated by Microsoft Visual Studio
 */

// Group=Examples

#include "stdafx.h"
#include "KDbgMacr.h" //Dump compiler-specific predefined macros

CTestLog g_logTest;   //general test logger

// Note: reference any additional headers you need in stdafx.h
// and not in this file

/*****************************************************************************
 * $Log:
 *  1    Biblioteka1.0         03/06/2004 2:29:39 PMDarko
 * $
 *****************************************************************************/
