/*$Workfile: stdafx.h$: header file
  $Revision: 14$  $Date: 2005-05-01 00:32:52$

  STandarD Application FrameworX
  header file includes standard system header files, or project specific header
  files that are used frequently, but are changed infrequently.
*/


#if !defined(_STDAFX_H_)
  /*$Workfile: stdafx.h$ sentry */
  #define _STDAFX_H_ 1544

#if __MWERKS__ >= 0x3000
  #pragma once
#endif //__MWERKS__ >= 0x3000

#ifdef _DEBUG_INCL_PREPROCESS   /*Preprocessor: debugging included files     */
  #pragma message ("   #include " __FILE__ )
#endif

#ifndef UNUSED_ARG
  #define UNUSED_ARG(param)    &(param)
#endif

//////////////////////////////////////////////////////////////////////////////
//Common header files

#if defined(__MWERKS__)/* Metrowerks CodeWarrior Compiler                    */

  #if defined (DEBUG) && !defined(_DEBUG)
    #define _DEBUG     //Enable library debugging messages
  #endif
  #if defined (_DEBUG) && !defined(DEBUG)
    #define DEBUG      //Enable CodeWarrior debugging messages
  #endif

  #include "assert.h"
  #include <stdlib.h>  /*includes EXIT_FAILURE, EXIT_SUCCESS from <cstdlib>  */

  #if __option (little_endian)
    /*Byte order, according to significance of bytes                         */
    #define _ENDIAN_ORDER_ _ENDIAN_LITTLE_
  #else
    /*Byte order, according to significance of bytes                         */
    #define _ENDIAN_ORDER_ _ENDIAN_BIG_
  #endif

  #ifndef _ENDIAN_ORDER_
    #ifdef _MSL_LITTLE_ENDIAN
      #if (_MSL_LITTLE_ENDIAN == 1)
        #define _ENDIAN_ORDER_ _ENDIAN_LITTLE_
      #elif (_MSL_LITTLE_ENDIAN == 0)
        #define _ENDIAN_ORDER_ _ENDIAN_BIG_
      #else
        #pragma message ("_MSL_: Unknown Endian byte order.")
      #endif
    #endif /*_MSL_LITTLE_ENDIAN*/
  #endif /*_ENDIAN_ORDER_*/

#endif

//-----------------------------------------------------------------------------
//PalmOS platforms

#include <PalmOS.h>
#include <PalmOSGlue.h>

#ifndef __PALMOS__
  #if defined (__MWERKS__)/*Metrowerks CodeWarrior Compiler*/
    #if  (__dest_os == __palm_os)
      #define __PALMOS__ 1
    #endif
  #endif
#endif

#if defined (_DEBUG)
  #ifndef _MSL_DEBUG
    //Metrowerks Standard Library debugging information included
    #define _MSL_DEBUG 1
  #endif
#else
  #undef REPORTER_TRACES
#endif

  /*Palm Reporter is an application which works in conjunction with
    the HostTrace APIs, and displays trace information generated by
    your application running on the Palm OS Emulator or Palm OS
    Simulator. To open a new Reporter window, first call HostTraceInit().
    To allow tracing using Reporter, assign 1 to the REPORTER_TRACES.

    See also: http://www.palmos.com/dev/tools/emulator/
   */
#if (REPORTER_TRACES == 1)
  //Palm Reporter console is required to display any tracing information
  #pragma message ("Palm Reporter is required.");
  #include <HostControl.h>
#endif

#ifdef __cplusplus
  //===========================================================================
  //Standard Template Library header files
  //For build dependant of the Standard Template Library (STL)
  #ifdef _STL
    #ifdef _DEBUG
      #ifndef _STLP_DEBUG
        #define _STLP_DEBUG 1    //Debug STLPort library
                                 //Note: have to be defined before STL header
                                 //files
      #endif
    #else
      #ifdef _STLP_DEBUG
        #undef _STLP_DEBUG
      #endif
    #endif

    /*Note: Include additional directory /I "..\..\STL\STLport\stlport" and
      appropriate STLport library in your make file, in order to replace
      compiler's native Standard Template Library.
     */

    #include "STL/KOStream.h" //ostream template, std::cout, std::endl
    #include <string>     //std::string

  //===========================================================================
  #endif //_STL
#else /*!__cplusplus (C compilation) */

  #ifdef __STDC__
    //ANSI C conformance (C99)
    #if defined (__MWERKS__)/*Metrowerks CodeWarrior Compiler*/
      #if !__option(c9x)
        //Compiler support for ISO C99 enabled
        #pragma c9x on
      #endif
    #endif

    #include <stdbool.h> //_Bool, bool typedef
  #else
    #include "KTypedef.h" /*_Bool, bool typedef*/
  #endif /*__STDC__ */

  #ifdef _CONSOLE
    #if (__dest_os == __mac_os)
     /*Include STL I/O - Simple Input and Output User eXchange (SIOUX)

       Linkage with following Metrowerks static libraries is required:

          PPC project:
             common                        minimum
          MSL_All_.PPC.Lib              MSL C.PPC.Lib
          InterfaceLib                  MSL C++.PPC.Lib (for C++)
          MathLib                       MSL_SIOUX_PPC.Lib
                                        MSL_Runtime_PPC.Lib
                                        InterfaceLib
                                        MathLib
          Carbon project:
             common                        minimum
          MSL_All_Carbon.Lib            MSL_C_Carbon.Lib
          CarbonLib                     MSL_C++_Carbon.Lib (for C++)
                                        MSL_SIOUX_Carbon.Lib
                                        CarbonLib
          Mach-O project:
             common                        minimum
          MSL_All_Mach-O.lib            MSL_C_Mach-O.lib
          MSL_SIOUX_Mach-O.lib          MSL_C++_Mach-O.lib (for C++)
                                        MSL_SIOUX_Mach-O.lib (to be implemented)
                                      MSL_Runtime_Mach-O.lib
      */
      #include <SIOUX.h>
    #endif
    #if (__dest_os == __win32_os)
      #include <WinSIOUX.h>
    #endif
  #endif //_CONSOLE
#endif //__cplusplus


///////////////////////////////////////////////////////////////////////////////
//Project specific header files
#include "KTrace.h"   /*ASSERT_CL macro                         */
#include "KTestLog.h" /*CTestLog class                          */

#include "Test_Rsc.h" /*Resource IDs                            */

// TODO: reference additional headers your program requires here

///////////////////////////////////////////////////////////////////////////////
#endif // !defined(_STDAFX_H_)
/*****************************************************************************
 * $Log:
 *  1    Biblioteka1.0         2004-10-19 14:54:17  Darko Kolakovic
 * $
 *****************************************************************************/
