/*$Workfile: StdPfhD_SBCS.h$: header file
  $Revision: 2$  $Date: 2004-11-05 13:26:53$

  Codewarrior standard prefix header file included before each source code
  Debugging Mode
  Copyright: CommonSoft Inc.
  Darko Kolakovic 2004-10-21
*/
/* Group=Diagnostic                                                          */


#ifdef __MWERKS__ /* Metrowerks CodeWarrior Compiler                    */
/* Note: to include this project settings before each source code file,
   open in CodeWarrior IDE following menu item:
      Edit : <project name> Settings... |
      Language Settings | C/C++ Language | Prefix file
      and type in edit box the name of this file
 */

  #if __MWERKS__ >= 0x3000
    #pragma once
  #endif //__MWERKS__ >= 0x3000

  #if !defined(_STDPFHD_H_)
    //$Workfile: StdPfhD_SBCS.h$ sentry
    #define _STDPFHD_H_

  #if (__dest_os == __palm_os)
    #ifndef __PALMOS__
      #define __PALMOS__ PALMOS_SDK_VERSION
    #endif
  #endif

  #undef  NDEBUG

  /*Note: to insert a debugger break point, in your application type in
    an empty line following shortcut: ..1 (<cursive l><dot><dot>1)
    It works only with Palm OS emulator or simulator.
   */
  #define DEBUG  1
  #define _DEBUG 1
  /*Enables Metrowerks Standard Library diagnostic messages.
   */
  #define _MSL_DEBUG

  /*Palm Reporter is an application which works in conjunction with
    the HostTrace APIs, and displays trace information generated by
    your application running on the Palm OS Emulator or Palm OS
    Simulator. To open a new Reporter window, first call HostTraceInit().
    To allow tracing using Reporter, assign 1 to the REPORTER_TRACES.
    
    See also: http://www.palmos.com/dev/tools/emulator/
   */
  #define REPORTER_TRACES 0

  #undef UNICODE
  #undef _UNICODE

  #ifndef ERROR_CHECK_LEVEL
     /*Enable macro that displays an error alert
       See also: ErrDisplay(), ErrFatalDisplayIf(),<ErrorMgr.h>
      */
    #define ERROR_CHECK_LEVEL ERROR_CHECK_FULL
  #endif

  #include "stdafx.h"

  #endif //_STDPFHD_H_
#endif //__MWERKS__
////////////////////////////////////////////////////////////////////////////////
