/*$Workfile: KAppEventProc.cpp$: implementation file
  $Revision: 1$ $Date: 2004-11-12 14:55:22$
  $Author: Darko Kolakovic$

  Event handler callback routine for the application
  Copyright: CommonSoft Inc.
  2004-10-21 Darko Kolakovic
 */

/* Group=Palm */

#include <PalmOS.h>
#include "stdafx.h"

#ifndef IDR_MAINFORM
  #error Application event processing requies IDR_MAINFORM resource to be defined!
#endif

  /*default event handler callback routine associated with the main form*/
extern FormEventHandlerType DefFormProc;

  /*event handler callback routine for the application*/
FormEventHandlerType AppEventProc;

//-----------------------------------------------------------------------------
/*This event handler procedure is an application-defined or library-defined
  callback function.
  The system calls this function after an input event occurs in a form,
  menu or scroll bar, but before the event message generated by the input event
  is processed. This routine is called from the event loop and default
  implementation includes loading main form form resources, set the event handler
  for the main form.

  Returns: true if the event was handled and no further processing is required;
  otherwise returns false.

  TODO: Set DefFormProc, IDR_MAINFORM, AppEventProc pointers in an extern function
  like SetWindowsHookEx()

  Note: Palm OS specific (PalmOS).
 */
Boolean AppEventProc(EventType* pEvent //[in] pointer to the event to
                                       //be processed
                             )
{
if (SysHandleEvent(pEvent))
  {
  return true;
  }
else
  {
      //Handle penDownEvent and keyDownEvent.events in the current menu
  UInt16 dummy;
  if (MenuHandleEvent(NULL,   //MenuBarType data structure
                       pEvent, //event to be processed
                       &dummy  //error code; currently is always zero
                       ))
    {
    return true;
    }
  else
    {
        /*Process other events*/
    switch (pEvent->eType)
      {
      case frmLoadEvent: /*The form load events*/
        {
        const UInt16 nFormId = pEvent->data.frmLoad.formID; /*required form*/
        switch (nFormId)
          {
          case IDR_MAINFORM: /*Set event handler for Main Form*/
            {
            /*Load the form resource.*/
            FormType* pForm = FrmInitForm(nFormId);
            /*Set the active form. All input (key and pen) is directed to
              the active form and all drawing occurs there.
             */
            FrmSetActiveForm(pForm);
            /*Set the event handler for the form. The handler of the currently
              active form is called by FrmHandleEvent each time it receives
              an event.
             */
            FrmSetEventHandler(pForm, DefFormProc);
            return true;
            }
          default:
            break;
         }
       }
      default:
        break;
      }
    }
  }

  /*Dispatch an unprocessed event to the active form's handler or to form
    specified in the event data by form's ID.
   */
return FrmDispatchEvent(pEvent);
}

///////////////////////////////////////////////////////////////////////////////
/*****************************************************************************
 * $Log: 
 *  1    Biblioteka1.0         2004-11-12 14:55:22  Darko Kolakovic 
 * $
 *****************************************************************************/
