/*$Workfile: KTracePalm.h$: implementation file
  $Revision: 1$ $Date: 2004-11-05 13:25:12$
  $Author: Darko Kolakovic$

  Debugging helpers
 */

/* Group=Diagnostic                                                          */

#ifndef _KTRACEPALM_H_
  /*$Workfile: KTracePalm.h$ sentry*/
  #define _KTRACEPALM_H_

#if __MWERKS__ >= 0x3000
  #pragma once
#endif //__MWERKS__ >= 0x3000

#ifdef _DEBUG_INCL_PREPROCESS   /*Preprocessor: debugging included files     */
  #pragma message ("   #include " __FILE__ )
#endif

/* ///////////////////////////////////////////////////////////////////////// */
/* // PalmOS 32-bit                                                          */
#if defined(__PALMOS__) || defined (__PALMOS_H__)


  #ifndef _DBG_WARN
    #define _DBG_WARN   1   /*Warning report type*/
  #endif
  #ifndef _DBG_ERROR
    #define _DBG_ERROR  2   /*Erroneous Condition report type*/
  #endif
  #ifndef _DBG_ASSERT
    #define _DBG_ASSERT 3  /*Assertation Failure report type*/
  #endif

  /* /////////////////////////////////////////////////////////////////////// */
  /* Debuging validation and text dump macros                                */

  /* ======================================================================= */
  /* Debug build version                                                     */
  #if defined (_DEBUG) || defined (DEBUG)

    /*........................................................................*/
    #if !defined(__ARMLET__) /*not an armlet, probably __MC68K__*/
      #include <ErrorMgr.h>

      #ifndef _DBG_BREAK
        /*Macro causes a debugger break after validating emulator fetures.

            sysFileCSystem                 'psys'
            kPalmOSEmulatorFeatureCreator  'pose'

        Note: Palm OS specific (PalmOS).
         */
        #define _DBG_BREAK() \
          {  \
          UInt32 __f; \
          if ( ( FtrGet( sysFileCSystem, sysFtrNumProcessorID, &__f ) != \
               ftrErrNoSuchFeature && __f == sysFtrNumProcessorx86 ) || \
             ( FtrGet( kPalmOSEmulatorFeatureCreator, \
                      kPalmOSEmulatorFeatureNumber, &__f ) !=  \
             ftrErrNoSuchFeature) ) \
            { \
            DbgBreak(); \
            } \
          }  ((void)0)
      #endif /*_DBG_BREAK*/

      #ifndef ASSERT
        /*This macro is compiled into the code only if the compiler define
          ERROR_CHECK_LEVEL is set to ERROR_CHECK_PARTIAL ( = 1) or
          ERROR_CHECK_FULL( = 2).
         */
        #define ASSERT(expr) \
          { \
          if (!(expr)) \
            { \
            _DBG_BREAK(); \
            ErrDisplayFileLineMsg( __FILE__, __LINE__, "Assertion failed."); \
            } \
          }
      #endif /*ASSERT*/
    #else /*__ARMLET__*/
    // #define ASSERT(expr) ??? TODO:
    /*........................................................................*/
    #endif /*!__ARMLET__*/

    #if !defined(REPORTER_TRACES) || (REPORTER_TRACES == 0)
      /*Send tracing messages to the debugger output window or log file.
        See also: DbgReport().
        */
      #include <DebugMgr.h>
      #ifndef LPCTSTR
        #include "KTChar.h"
      #endif
      #ifdef __cplusplus
        extern "C" void DbgReport( int iReportType,
                LPCTSTR szFileName,
                unsigned int nLineNumber, 
                LPCTSTR szModuleName, 
                LPCTSTR szMessage,
                ...);
      #else
        void DbgReport( int iReportType,
                LPCTSTR szFileName,
                unsigned int nLineNumber, 
                LPCTSTR szModuleName, 
                LPCTSTR szMessage,
                ...);
      #endif
      #ifndef TRACE
        #define TRACE(...) \
            DbgReport( _DBG_WARN, NULL, 0, NULL, __VA_ARGS__)
      #endif
      #ifndef TRACE0
        #define TRACE0( szMsg) \
            DbgReport( _DBG_WARN, NULL, 0, NULL, szMsg)
      #endif
      #ifndef TRACE1
        #define TRACE1( szMsg, p1) \
            DbgReport( _DBG_WARN, NULL, 0, NULL, szMsg, p1)
      #endif
      #ifndef TRACE2
        #define TRACE2( szMsg, p1, p2) \
            DbgReport( _DBG_WARN, NULL, 0, NULL, szMsg, p1, p2)
      #endif
      #ifndef TRACE3
        #define TRACE3( szMsg, p1, p2, p3) \
            DbgReport( _DBG_WARN, NULL, 0, NULL, szMsg, p1, p2, p3)
      #endif
      #ifndef TRACEINFO
        #define TRACEINFO(...) \
            DbgReport(_DBG_WARN, __FILE__, __LINE__, NULL, __VA_ARGS__ )
      #endif
    #endif /*!REPORTER_TRACES*/

    /*........................................................................*/
    #if (REPORTER_TRACES == 1)
      /*Palm Reporter is an application which works in conjunction with
        the HostTrace APIs, and displays trace information generated by
        your application running on the Palm OS Emulator or Palm OS
        Simulator. To open a new Reporter window, first call HostTraceInit().
        To allow tracing using Reporter, assign 1 to the REPORTER_TRACES.

        See also: http://www.palmos.com/dev/tools/emulator/
       */
      #include <HostControl.h>

      #ifndef TRACE
        #define TRACE(...) HostTraceOutputT(appErrorClass,__VA_ARGS__)
      #endif

      #ifndef TRACEINFO
        #define TRACEINFO(...) HostTraceOutputT(appErrorClass,"%s(%i): ",__TFILE__, __LINE__); \
            HostTraceOutputT(appErrorClass,__VA_ARGS__)
      #endif

      #ifndef TRACE0
        #define TRACE0(msg) HostTraceOutputT(appErrorClass, msg)
      #endif
      #ifndef TRACE1
        #define TRACE1(format,param1) HostTraceOutputT(appErrorClass,format,param1)
      #endif
      #ifndef TRACE2
        #define TRACE2(format,param1,param2) HostTraceOutputT(appErrorClass,format,param1,param2)
      #endif
      #ifndef TRACE3
        #define TRACE3(format,p1, p2, p3) HostTraceOutputT(appErrorClass,format,p1, p2, p3)
      #endif

    /*........................................................................*/
    #endif /*(REPORTER_TRACES == 1)*/


  /* ======================================================================= */
  /* Release (non-debug) build version                                       */
  #else /* NDEBUG */
    #if defined(__MWERKS__)/* Metrowerks CodeWarrior Compiler                */
       #ifndef TRACEINFO
        #define TRACEINFO(...) do{}while(0) //Won't generate any code
      #endif
      #ifndef TRACE
        #define TRACE(...)     do{}while(0) //Won't generate any code
      #endif
    #endif

    #ifndef TRACE
      #define TRACE(format)
    #endif
    #ifndef TRACE0
      #define TRACE0(format)
    #endif
    #ifndef TRACE1
      #define TRACE1(format,param1)
    #endif
    #ifndef TRACE2
      #define TRACE2(format,param1,param2)
    #endif
    #ifndef TRACE3
      #define TRACE3(format,p1, p2, p3)
    #endif
    #ifndef TRACEINFO
      #define TRACEINFO(format)
    #endif
    #ifndef ASSERT
      #define ASSERT(exp)
    #endif

  /* ======================================================================= */
  #endif  /*!_DEBUG */

/* ///////////////////////////////////////////////////////////////////////// */
#else
    #error "Included PalmOS specfic header file."
#endif /*__PALMOS__*/

/* ///////////////////////////////////////////////////////////////////////// */
#endif /*_KTRACEPALM_H_*/
/*****************************************************************************
 * $Log:
 *  1    Biblioteka1.0         2004-11-04 16:45:14  Darko Kolakovic
 * $
 *****************************************************************************/
