VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "clsSrcPool"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
'$Workfile: KWinUser32.bas$: implementation file
'$Revision: 2$ $Date: 2007-04-20 14:28:36$
'$Author: Darko Kolakovic$
'
'SrcPool DLL
'2007-04-11


'///////////////////////////////////////////////////////////////////////////////
'*******************************************************************************
'$Log: $
'*******************************************************************************

