/*$Workfile: main.cpp$: implementation file
  $Revision: 8$ $Date: 2007-03-08 20:40:27$
  $Author: Darko Kolakovic$

  COM container to test ATL DLL.
  Copyright: CommonSoft Inc.
  2006-01-12 Darko Kolakovic
*/

// Group=Examples

#include "stdafx.h"
#include <tchar.h>  //TCHAR
#include <stdlib.h> //EXIT_SUCCESS
#include <iostream>
#include "STL/KOStream.h" //_tcout
#include "KTestLog.h"
#include <objbase.h>
#ifndef _WIN32_DCOM
  #define COINIT_MULTITHREADED  0x0  // OLE calls objects on any thread.
#endif 
  //#include "Resource.h"

#ifdef _DEBUG
  //#define new DEBUG_NEW
  #undef THIS_FILE
  static char THIS_FILE[] = __FILE__;
#endif

#define _USE_MIDL_OUTPUT //Use files generated by MIDL
#ifdef _USE_MIDL_OUTPUT
//Files generated by MIDL compiler
  #include "TestComAtl.h"
  #include "TestComAtl_i.c" //CLSID_TestAtlObj
#else
  //Incorporate information from a type library (.tlb , .odl) or file (.dll, .ocx, .exe)
  //containing a type library resource
  //Fixme! #import "TestComAtl.dll" no_namespace
#endif
/////////////////////////////////////////////////////////////////////////////
#ifdef _MSC_VER     /*Microsoft Visual Studio C/C++ compiler                 */
  #ifndef _CONSOLE
    #error "define _CONSOLE macro in the project"
  #endif
#endif

extern uint_least32_t ComGetThreadingModel();
extern bool TestCHresult();
extern bool TestMethod();
extern bool TestComEvents();
//extern bool TsWriteToViewLn(LPCTSTR lszText); TODO:

//-----------------------------------------------------------------------------
/*Test ATL COM container.
  Defines the entry point for the console application.
  This application is an ActiveX client.or subscriber. The ActiveX clients can 
  access objects by calling functions exported through COM object's virtual 
  function table (VTBL) or by using the IDispatch interface (late binding).

  Returns: EXIT_SUCCESS, which represents a value of 0, if successful. Otherwise
  a non-zero error code is returned.

  Note: uses Active Template Library (ATL);
        Microsoft Windows specific (Win32).
 */
int _tmain(int argc,      //[in] specifies how many arguments are passed to the
                          //program from the command line. The value of argc is
                          //at least one: the program name.
           TCHAR* argv[], //[in] the program arguments as an array of pointers
                          //to null-terminated strings. The first string
                          //(argv[0]) is the program name. The end of the array
                          //(argv[argc]) is indicated by a NULL pointer.
           TCHAR* envp[]  //[in] the user's environment variables as a pointer
                          //to an array of null-terminated strings. The end of
                          //the array is indicated by a NULL pointer.
                          //Note: Microsoft Windows specific (Win).
           )
{
int nRetCode = EXIT_SUCCESS;

//TODO: testing loop
std::_tcout << _T("Test HRESULT validation") << std::endl;
if(!TestCHresult())
  nRetCode = EXIT_FAILURE;

std::_tcout << _T("Creating COM object...") << std::endl;
 //Initialize COM
#if _WIN32_WINNT >= 0x0400 & defined(_ATL_FREE_THREADED)
  HRESULT hResult = CoInitializeEx(NULL, COINIT_MULTITHREADED);
#else
  HRESULT hResult = CoInitialize(NULL);
#endif

if(SUCCEEDED(hResult))
  {
  //Test apartment model
  switch (ComGetThreadingModel())
    {
    case COINIT_MULTITHREADED:
      std::_tcout << _T("Multi-threaded Apartment type.") << std::endl;
      break;
    case COINIT_APARTMENTTHREADED:
      std::_tcout << _T("Apartment-threaded Apartment type.") << std::endl;
      break;
    case 0xFF: //COGET_NOT_INTIALIZED
      std::_tcout << _T("COM library is not initialized.") << std::endl;
      break;
    default:
      std::_tcout << _T("unknown Apartment type.") << std::endl;
    }
    
  //Test in-process server object
  ITestAtlObj* pcomTest = NULL;
  hResult = CoCreateInstance( CLSID_TestAtlObj,//coclass guid  used to create
                                               //the object.
                              NULL,
                              CLSCTX_INPROC_SERVER, //.dll COM could run either
                                      //as an in-process or as an out-of-process
                              IID_ITestAtlObj,
                              (void**)& pcomTest);

  if(SUCCEEDED(hResult))
    {
    long lResult;
    pcomTest->TestMethod(7, &lResult);
    std::_tcout << _T("2 * 7 = ") << lResult << std::endl;
    pcomTest->Release();
    }
  else
    {
    std::_tcout << _T("CoCreateInstance() failed!") << std::endl;
    nRetCode = EXIT_FAILURE;
    }
  std::_tcout << LOG_EOT << std::endl;
  
   //Test out-of-process server
  if(!TestMethod())
    nRetCode = EXIT_FAILURE;
  if(!TestComEvents())
    nRetCode = EXIT_FAILURE;
  }
CoUninitialize(); //Uninitialize COM

std::_tcout << _T("Fin") << std::endl;
return nRetCode;
}

///////////////////////////////////////////////////////////////////////////////
/******************************************************************************
 * $Log:
 *  4    Biblioteka1.3         2007-02-21 09:15:31  Darko Kolakovic TestCHresult
 *  3    Biblioteka1.2         2007-02-15 20:36:32  Darko Kolakovic ITestAtl7Obj
 *  2    Biblioteka1.1         2007-02-13 13:44:58  Darko Kolakovic Changed Test
 *       object
 *  1    Biblioteka1.0         2007-02-12 19:24:54  Darko Kolakovic
 * $
 *****************************************************************************/
