/*$Workfile: main.cpp$: implementation file
  $Revision: 4$ $Date: 2007-02-21 09:15:31$
  $Author: Darko Kolakovic$

  COM container to test ATL DLL.
  Copyright: CommonSoft Inc.
  2006-01-12 Darko Kolakovic
*/

// Group=Examples

#include "stdafx.h"
#include <tchar.h>  //TCHAR
#include <stdlib.h> //EXIT_SUCCESS
#include <iostream>
#include "STL/KOStream.h" //_tcout

  //#include "Resource.h"

#ifdef _DEBUG
  #define new DEBUG_NEW
  #undef THIS_FILE
  static char THIS_FILE[] = __FILE__;
#endif

#define _USE_MIDL_OUTPUT //Use files generated by MIDL
#ifdef _USE_MIDL_OUTPUT
//Files generated by MIDL compiler
  #include "TestComAtl.h"
  #include "TestComAtl_i.c" //CLSID_TestAtlObj
  
  #include "TestComAtlNet.h"
  #include "TestComAtlNet_i.c"
#else
  //Incorporate information from a type library (.tlb , .odl) or file (.dll, .ocx, .exe) 
  //containing a type library resource
  //Fixme! #import "TestComAtl.dll" no_namespace
#endif
/////////////////////////////////////////////////////////////////////////////
#ifdef _MSC_VER     /*Microsoft Visual Studio C/C++ compiler                 */
  #ifndef _CONSOLE
    #error "define _CONSOLE macro in the project"
  #endif
#endif

extern bool TestCHresult();
//extern bool TsWriteToViewLn(LPCTSTR lszText); TODO:

//-----------------------------------------------------------------------------
/*Test ATL COM container.
  Defines the entry point for the console application.

  Returns: EXIT_SUCCESS, which represents a value of 0, if successful. Otherwise
  a non-zero error code is returned.

  Note: uses Active Template Library (ATL);
        Microsoft Windows specific (Win32).
 */
int _tmain(int argc,      //[in] specifies how many arguments are passed to the
                          //program from the command line. The value of argc is
                          //at least one: the program name.
           TCHAR* argv[], //[in] the program arguments as an array of pointers
                          //to null-terminated strings. The first string 
                          //(argv[0]) is the program name. The end of the array
                          //(argv[argc]) is indicated by a NULL pointer.
           TCHAR* envp[]  //[in] the user's environment variables as a pointer 
                          //to an array of null-terminated strings. The end of
                          //the array is indicated by a NULL pointer. 
                          //Note: Microsoft Windows specific (Win).
           )
{
int nRetCode = EXIT_SUCCESS;

//TODO: testing loop
std::_tcout << _T("Test HRESULT validation") << std::endl;
TestCHresult();

std::_tcout << _T("Creating COM object...") << std::endl;
HRESULT hResult = CoInitialize(NULL); //Initialize COM
if(SUCCEEDED(hResult))
  {
  ITestAtlObj* pcomTest = NULL;
  hResult = CoCreateInstance( CLSID_TestAtlObj, 
                              NULL, 
                              CLSCTX_INPROC_SERVER, //.dll COM could run either 
                                      //as an in-process or as an out-of-process
                              IID_ITestAtlObj, 
                              (void**)& pcomTest);

  if(SUCCEEDED(hResult))
    {
    long lResult;
    pcomTest->TestMethod(7, &lResult);
    std::_tcout << _T("2 * 7 = ") << lResult << std::endl;
    pcomTest->Release(); 
    }
  else
    {
    std::_tcout << _T("CoCreateInstance() failed!") << std::endl;
    }
    
  //
  ITestAtl7Obj* pcomTest7 = NULL;
  hResult = CoCreateInstance( CLSID_TestAtl7Obj, 
                              NULL, 
                              CLSCTX_ALL, //.exe COM could run only as local 
                                          //or remote out-of-process server
                              IID_ITestAtl7Obj, 
                              (void**)& pcomTest7);

  if(SUCCEEDED(hResult))
    {
    long lResult;
    pcomTest7->TestMethod(7, &lResult);
    std::_tcout << _T("2 + 7 = ") << lResult << std::endl;
    pcomTest7->Release(); 
    }
  else
    {
    std::_tcout << _T("CoCreateInstance() of TestAtl7Obj failed!") << std::endl;
    }
  }
CoUninitialize(); //Uninitialize COM

std::_tcout << _T("Fin") << std::endl;
return nRetCode;
}

///////////////////////////////////////////////////////////////////////////////
/******************************************************************************
 * $Log: 
 *  4    Biblioteka1.3         2007-02-21 09:15:31  Darko Kolakovic TestCHresult
 *  3    Biblioteka1.2         2007-02-15 20:36:32  Darko Kolakovic ITestAtl7Obj
 *  2    Biblioteka1.1         2007-02-13 13:44:58  Darko Kolakovic Changed Test
 *       object
 *  1    Biblioteka1.0         2007-02-12 19:24:54  Darko Kolakovic 
 * $
 *****************************************************************************/
