/*$Workfile: main.cpp$: implementation file
  $Revision: 2$ $Date: 2007-02-13 13:44:58$
  $Author: Darko Kolakovic$

  COM container to test ATL DLL.
  Copyright: CommonSoft Inc.
  2006-01-12 Darko Kolakovic
*/

// Group=Examples

#include "stdafx.h"
#include <tchar.h>  //TCHAR
#include <stdlib.h> //EXIT_SUCCESS
#include <iostream>

  //#include "Resource.h"

#ifdef _DEBUG
  #define new DEBUG_NEW
  #undef THIS_FILE
  static char THIS_FILE[] = __FILE__;
#endif

//Files generated by MIDL compiler
#include "TestComAtl.h"
#include "TestComAtl_i.c" //CLSID_TestAtlObj
//or to load the typelib from the dll

//#import "TestComAtl.dll" no_namespace
/////////////////////////////////////////////////////////////////////////////
#ifdef _MSC_VER     /*Microsoft Visual Studio C/C++ compiler                 */
  #ifndef _CONSOLE
    #error "define _CONSOLE macro in the project"
  #endif
#endif

//extern bool TsWriteToViewLn(LPCTSTR lszText);
//extern int TestCommonConsole(int argc, TCHAR* argv[]);

//-----------------------------------------------------------------------------
/*Test ATL COM container.
  Defines the entry point for the console application.

  Returns: EXIT_SUCCESS, which represents a value of 0, if successful. Otherwise
  a non-zero error code is returned.

  Note: uses Active Template Library (ATL);
        Microsoft Windows specific (Win32).
 */
int _tmain(int argc,      //[in] specifies how many arguments are passed to the
                          //program from the command line. The value of argc is
                          //at least one: the program name.
           TCHAR* argv[], //[in] the program arguments as an array of pointers
                          //to null-terminated strings. The first string 
                          //(argv[0]) is the program name. The end of the array
                          //(argv[argc]) is indicated by a NULL pointer.
           TCHAR* envp[]  //[in] the user's environment variables as a pointer 
                          //to an array of null-terminated strings. The end of
                          //the array is indicated by a NULL pointer. 
                          //Note: Microsoft Windows specific (Win).
           )
{
int nRetCode = EXIT_SUCCESS;



std::cout << "Creating COM object..." << std::endl;
HRESULT hResult = CoInitialize(NULL); //Initialize COM
if(SUCCEEDED(hResult))
  {
  ITestAtlObj* pcomTest = NULL;
  hResult = CoCreateInstance( CLSID_TestAtlObj, 
                              NULL, 
                              CLSCTX_INPROC_SERVER,
                              IID_ITestAtlObj, 
                              (void**)& pcomTest);

  if(SUCCEEDED(hResult))
    {
    long lResult;
    pcomTest->TestMethod(7, &lResult);
    std::cout << "2 * 7 = " << lResult << std::endl;
    pcomTest->Release(); 
    }
  else
    {
    std::cout << "CoCreateInstance() failed!" << std::endl;
    }
  }

CoUninitialize(); //Uninitialize COM

return nRetCode;
}

///////////////////////////////////////////////////////////////////////////////
/******************************************************************************
 * $Log: 
 *  2    Biblioteka1.1         2007-02-13 13:44:58  Darko Kolakovic Changed Test
 *       object
 *  1    Biblioteka1.0         2007-02-12 19:24:54  Darko Kolakovic 
 * $
 *****************************************************************************/
