/*$Workfile: KZLineIn.cpp$: implementation file
  $Revision: 9$ $Date: 2007-05-25 17:24:14$
  $Author: Darko Kolakovic$

  Line impedance calculation
  Copyright: CommonSoft Inc.
  May 94 Darko Kolakovic
  Feb 2k revision D.K.
 */ 

/*TODO: Bizarre Visual C++ 6.0 problem: without precompiled header following warnings
  are generated by standard C++ headers:
  C4100: unreferenced formal parameter
  C4663: C++ language change:
  C4018: signed/unsigned mismatch
  C4244: conversion from 'unsigned int' to 'char'
  C4146: unary minus operator applied to unsigned type
  C4511: copy constructor could not be generated
  C4512: assignment operator could not be generated
  C4275: non dll-interface class 'std::_Complex_base<double>' used as base for dll-interface class
  Feb. 2k D.K.

  If precompiled header is enabled (/Yu"stdafx.h" switch) and header is
  between #if and #endif following error is generated :
  fatal error C1020: unexpected #endif
  #if 1
    #include "stdafx.h"
  #endif
  Feb 2k D.K.
 */
#if (_MSC_VER >= 1200) //VC++ 6.0
  #if (_MSC_VER < 1300) //VC++.Net 7.0
    #include "stdafx.h"
  #endif
#endif

#include "KComplex.h"   //CComplex class
#include "KPhysCst.h"   //constants
#include "KProgCst.inl" //NaN

#ifdef _DEBUG
  #define new DEBUG_NEW
  #undef THIS_FILE
  static char THIS_FILE[] = __FILE__;
#endif

//GetLineZin()-----------------------------------------------------------------
/*Calculates a Transmission Line Input Impedance. 
  {html: It is assumed that the transmission line is linear and uniform along
  its length. A transmission line could be replaced with an equivalent quadrupole
  defined by its characteristic impedance <i>Z<sub>0</sub></i>.
  <img src="Images/diagTransmissionLine.gif" alt="quadrupole" title="quadrupole" /><br />
  <!--      +---------------------------------------+
      -Zin--+  Z0(length, phase shift, attenuation) +--ZL-+ Terminating impedance
         +--+                                       +-----+
      ---+  +---------------------------------------+
   -->
  The characteristic (surge) impedance of a uniform transmission line is:<br />
  <img src="Images/eqZ0.gif" alt="Z0=sqtrt((R+j&omega;L)/(G+j&omega;L))" /><br /.
  where:<dl>
    <dd><i>R</i> is the resistance per unit length,</dd>
    <dd><i>L</i> is the inductance per unit length,</dd>
    <dd><i>G</i> is the conductance of the dielectric per unit length,</dd>
    <dd><i>C</i> is the capacitance per unit length,
    <dd><i>j</i> is the imaginary unit,</dd>
    <dd><i>&omega;</i> is the angular frequency.</dd></dl>

   The input impedance is calculated as:<br />
   <img src="Images/eqZin.gif" alt="Zin=Z0((ZL+Z0 tanh(&gamma;l))/(Z0+ZL tanh(&gamma;l)))" /><br />
    Zin = Z0 * tanh[&gamma;*dLineLength + atanh(ZL / Z0)]

  where:<dl>
    <dd><i>&gamma;</i>[&Omega;/m] is the line propagation constant
    <img src="Images/eqPropCst.gif" alt="&gamma; = dAttenuation + j*dPhaseShift" /><br />
    <img src="Images/eqPropCst1.gif" alt="&gamma; = loss [dB/m] + j*dPhaseCst" /></dd>
    <dd><i>&alpha;</i> is attenuation constant representing signal loss in the conductor
      and dielectric signal loss per length unit
      <img src="Images/eqLineLoss.gif" alt="&alpha;[dB/m] = -ln(10e(&aplha;/20))" />,</dd>
    <dd><i>&beta;</i> is phase constant representing change in phase of
    the signal per length unit
      <img src="Images/eqLinePhase.gif" alt="&beta;[m/s] = 2&pi;f/v" />,</dd>
    <dd><i>Z<sub>L</sub></i> is the terminating impedance or load,</dd>
    <dd><i>Z<sub>0</sub></i> is the characteristic impedance of the line,</dd>
    <dd><i>Z<sub>in</sub></i> is input impedance or impedance of the signal source.</dd></dl>}
 */
CComplex GetLineZin(CComplex        ZL,          //[in] terminating impedance
                    const CComplex& Z0,          //[in] line characteristic impedance
                    double          dAttenuation,//[in] signal loss as it travels 
                    //over the transmission line [dB/m]
                    double          dPhaseShift, //[in] propagation velocity of 
                    //a uniform plane wave on the transmission line [m/s]
                    const double&   dLineLength  //[in] line length [m]
                    )
{
CComplex Zin(0., 0.); //Result
if (Z0 == 0.)   //If Z0 == 0 +j0
  {
  Zin.real(CST_dNaN);
  Zin.imag(CST_dNaN);
  return Zin;
  }

  //Get attenuation and phase shift of line
dAttenuation *= dB2Np(dLineLength);
dPhaseShift  *= dLineLength;

if (ZL != 0.) //if ZL != 0 +j0
  {
  Zin = ZL / Z0;
  Zin = atanh(Zin);
  }

  //Add line propagation impedance
Zin.real(Zin.real()+ dAttenuation);
Zin.imag(Zin.imag()+  dPhaseShift);
Zin = tanh(Zin); //Calculate  hyperbolic tangent
Zin *= Z0;

return Zin; //Return input impedance
}

///////////////////////////////////////////////////////////////////////////////
/******************************************************************************
 * $Log: 
 *  9    Biblioteka1.8         2007-05-25 17:24:14  Darko Kolakovic Comment
 *  8    Biblioteka1.7         2007-05-24 07:48:31  Darko Kolakovic Complex 0
 *       initialization
 *  7    Biblioteka1.6         2004-06-01 16:54:56  Darko           StdAfx changed
 *       to stdafx
 *  6    Biblioteka1.5         2003-08-22 16:59:47  Darko           comment
 *  5    Biblioteka1.4         2003-01-30 22:43:43  Darko           Excluded
 *       stdafx.h
 *  4    Biblioteka1.3         2002-01-25 16:59:57  Darko           Updated
 *       comments
 *  3    Biblioteka1.2         2001-07-11 22:53:49  Darko           
 *  2    Biblioteka1.1         2001-06-08 23:52:44  Darko           VSS
 *  1    Biblioteka1.0         2000-08-13 16:04:31  Darko           
 * $
 *****************************************************************************/