/*$Workfile: KZLineIn.cpp$: implementation file
  $Revision: 4$ $Date: 1/25/02 4:59:57 PM$
  $Author: Darko$

  Line impedance calculation
  Copyright: CommonSoft Inc.
  May 94 Darko Kolakovic
  Feb 2k revision D.K.
 */ 

/*TODO: Bizarre Visual C++ 6.0 problem: without precompiled header following warnings
  are generated by standard C++ headers:
  C4100: unreferenced formal parameter
  C4663: C++ language change:
  C4018: signed/unsigned mismatch
  C4244: conversion from 'unsigned int' to 'char'
  C4146: unary minus operator applied to unsigned type
  C4511: copy constructor could not be generated
  C4512: assignment operator could not be generated
  C4275: non dll-interface class 'std::_Complex_base<double>' used as base for dll-interface class
  Feb. 2k D.K.

  If precompiled header is enabled (/Yu"StdAfx.h" switch) and header is
  between #if and #endif following error is generated :
  fatal error C1020: unexpected #endif
  #if 1
    #include "StdAfx.h"
  #endif
  Feb 2k D.K.
 */
#include "StdAfx.h"

#include "KComplex.h"   //CComplex class
#include "KPhysCst.h"   //constants
#include "KProgCst.inl" //NaN

#ifdef _DEBUG
  #define new DEBUG_NEW
  #undef THIS_FILE
  static char THIS_FILE[] = __FILE__;
#endif

//GetLineZin()-----------------------------------------------------------------
/*Calculates a Transmission Line Input Impedance.

    Zin = Zline * tanh[Zcst*dLineLength + atanh(Zt / Zline)]

    Zcst = dAttenuation + j*dPhaseShift
    Zi      the line input impedance to the line,
    Zcst    the line propagation constant [ohm/length_unit]
    Zline   the line characteristic impedance of the line
    Zt      the line terminating impedance

     |      +---------+
     |      |         |
     |    --+  Zline, +---+
     |      | length, |   |
     |      |  phase  |  +++
     |   Zin|  shift, |  | |Terminating impedance
     |      | attenu- |  | |Zt
     |      | ation   |  +++
     |      |         |   |
     |    --+         +---+
     |      |         |
     |      +---------+
 */
CComplex GetLineZin(CComplex        Zt,          //terminating impedance
                    const CComplex& Zline,       //line characteristic impedance
                    double          dAttenuation,//line attenuation per unit of
                                                 //length  [dB/length_unit]
                    double          dPhaseShift, //phase shift per unit of
                                                 //length [rad/length_unit]
                    const double&   dLineLength  //line length [length_unit]
                    )
{
CComplex Zin(0,0); //Result
if (Zline == 0.)   //If Zline == 0 +j0
  {
  Zin.real(CST_dNaN);
  Zin.imag(CST_dNaN);
  return Zin;
  }

  //Get attenuation and phase shift of line
dAttenuation *= dB2Np(dLineLength);
dPhaseShift  *= dLineLength;

if (Zt != 0.) //if Zt != 0 +j0
  {
  Zin = Zt / Zline;
  Zin = atanh(Zin);
  }

  //Add line propagation impedance
Zin.real(Zin.real()+ dAttenuation);
Zin.imag(Zin.imag()+  dPhaseShift);
Zin = tanh(Zin); //Calculate  hyperbolic tangent
Zin *= Zline;

return Zin;
}

///////////////////////////////////////////////////////////////////////////////