/*$Workfile: TestAboutDlg.h$: header file
  $Revision: 3$ $Date: 2005-04-26 12:00:46$
  $Author: Darko Kolakovic$

  Interface of the CAboutDlg class
  Copyright: CommonSoft Inc
  2003-08-25 Darko Kolakovic
 */

// Group=Examples Windows

#pragma once

#ifndef __AFXWIN_H__
  #error include 'stdafx.h' before including this file for PCH
#endif

#include "Resource.h"   // main symbols

///////////////////////////////////////////////////////////////////////////////
//Plain 'About' dialog automatically generated by IDE.
//
//Note: uses Microsoft Foundation Library (MFC);
//      Microsoft Windows specific (Win).
class CAboutDlg : public CDialog
{
public:
  CAboutDlg();
  virtual ~CAboutDlg();

// Dialog Data
  enum { IDD = IDD_ABOUTBOX };

protected:
  virtual void DoDataExchange(CDataExchange* pDX);    // DDX/DDV support

// Implementation
protected:
  DECLARE_MESSAGE_MAP()
};

///////////////////////////////////////////////////////////////////////////////
/*****************************************************************************
 * $Log:
 *  2    Biblioteka1.1         2003-08-27 18:11:55  Darko           renamed class
 *  1    Biblioteka1.0         2003-08-26 01:37:12  Darko
 * $
 *****************************************************************************/
