/*$RCSfile: TestAtlAboutDlg.h,v $: header file
  $Revision: 1.3 $ $Date: 2009/02/24 21:42:33 $
  $Author: ddarko $

  Interface of the CAboutDlg class
 */

// Group=Examples Windows

#pragma once

#ifdef _DEBUG_INCL_PREPROCESS   //Preprocessor: debugging included files
  #pragma message ("   #include " __FILE__ )
#endif

#ifndef IDD_ABOUTBOX
  #include "../Res/TestAboutDlg.h"
#endif
////////////////////////////////////////////////////////////////////////////////
//Plain 'About' dialog automatically generated by WTL Wizard in IDE.
//
//Note: uses Microsoft Active Template Library (ATL);
//      Windows Template Library (WTL);
//      Microsoft Windows specific (Win32).
class CAboutDlg : public CDialogImpl<CAboutDlg>
{
public:
  enum { IDD = IDD_ABOUTBOX };

  BEGIN_MSG_MAP(CAboutDlg)
    MESSAGE_HANDLER(WM_INITDIALOG, OnInitDialog)
    COMMAND_ID_HANDLER(IDOK, OnCloseCmd)
    COMMAND_ID_HANDLER(IDCANCEL, OnCloseCmd)
  END_MSG_MAP()

// Handler prototypes (uncomment arguments if needed):
//  LRESULT MessageHandler(UINT /*uMsg*/, WPARAM /*wParam*/, LPARAM /*lParam*/, BOOL& /*bHandled*/)
//  LRESULT CommandHandler(WORD /*wNotifyCode*/, WORD /*wID*/, HWND /*hWndCtl*/, BOOL& /*bHandled*/)
//  LRESULT NotifyHandler(int /*idCtrl*/, LPNMHDR /*pnmh*/, BOOL& /*bHandled*/)

  LRESULT OnInitDialog(UINT /*uMsg*/, WPARAM /*wParam*/, LPARAM /*lParam*/, BOOL& /*bHandled*/);
  LRESULT OnCloseCmd(WORD /*wNotifyCode*/, WORD wID, HWND /*hWndCtl*/, BOOL& /*bHandled*/);
};
///////////////////////////////////////////////////////////////////////////////
/******************************************************************************
 * $Log: TestAtlAboutDlg.h,v $
 * Revision 1.3  2009/02/24 21:42:33  ddarko
 * Test common control notification messages
 *
 * Revision 1.2  2009/02/23 20:06:44  ddarko
 * Test application for  ATL/WTL controls
 *
 ******************************************************************************/
