/*$Workfile: TestPredefinedMacrosC.c$: implementation file
  $Revision: 4$ $Date: 2004-11-09 18:46:11$
  $Author: Darko Kolakovic$

  Test compiler defined macros.
  Copyright: CommonSoft Inc.
  2004-08-31 Darko Kolakovic
*/

/* Group=Examples                                                            */

  /*Verfy if boolean types are defined. 
    See also <stdbool.h>
   */
#if defined(__MWERKS__)/* Metrowerks CodeWarrior Compiler                    */
  #define _VALIDATE_BOOLEN_TYPE  11
#endif
#include "stdafx.h"
#include "KDbgMacr.h" /*Dump compiler-specific predefined macros*/
#include "KTrace.h"   /*ASSERT_CL macro                         */
#include "KTypedef.h" /*__WFILE__ macro                         */

static const wchar_t *s_pwszFILE = __WFILE__;

extern bool TsWriteToViewLn(LPCTSTR lszText);
bool TestPredefinedMacrosC();

#ifdef __cplusplus
  /*Requires C compilation*/
  ASSERT_CL(false);
#endif
/*---------------------------------------------------------------------------*/
/*Test predefined macros in C compiler. These macros take no arguments and 
  cannot be redefined. Their value (except for __LINE__ and __FILE__) must be 
  constant throughout compilation. Some of the predefined macros listed below 
  are defined with multiple values.
  The compilers should recognize predefined ANSI C macros (see Table 1.1).

      Table 1.1   ANSI-Compliant Predefined Macros

      Macro         Description 
      __DATE__      The compilation date of the current source file. The date
                    is a string literal of the form Mmm dd yyyy. The month name
                    Mmm is the same as for dates generated by the library
                    function asctime() declared in <time.h>.
      __FILE__      The name of the current source file. __FILE__ expands to
                    a string surrounded by double quotation marks.
      __FUNCTION__  Valid only within a function and returns the undecorated
                    name of the enclosing function (as a string).
                    Note: Microsoft specific: __FUNCTION__ is not expanded if 
                    you use /EP or /P compiler options. 
      __LINE__      The line number in the current source file. The line number
                    is a decimal integer constant. It can be altered with a #line
                    directive.
      __STDC__      Indicates full conformance with the ANSI C standard.
                    Defined if you are not compiling C++ code and if you require
                    ANSI conformance. Otherwise is undefined.
                    Note: Microsoft specific: Defined as the integer constant 1
                    only if the /Za compiler option is given.
      __TIME__      The most recent compilation time of the current source file.
                    The time is a string literal of the form hh:mm:ss.  
      __TIMESTAMP__ The date and time of the last modification of the current
                    source file, expressed as a string literal in the form 
                    Ddd Mmm Date hh:mm:ss yyyy, where Ddd is the abbreviated
                    day of the week and Date is an integer from 1 to 31. 


  The Microsoft C/C++ implementation provides several more predefined macros
  (see Table 1.2).

      Table 1.2   Some of the Microsoft-Specific Predefined Macros 

      Macro           Description 
      _CHAR_UNSIGNED  Default char type is unsigned.
                      Defined when /J is specified.  
      __cplusplus     Defined for C++ programs only. 
      _CPPRTTI        Defined for code compiled with /GR 
                      (Enable Run-Time Type Information). 
      _CPPUNWIND      Defined for code compiled with /GX 
                      (Enable Exception Handling). 
      _DLL            Defined when /MD or /MDd (Multithread DLL) is specified. 
      _M_ALPHA        Defined for DEC ALPHA platforms. It is defined as 1 by
                      the ALPHA compiler, and it is not defined if another
                      compiler is used. 
      _M_IX86         Defined for x86 processors.
      _M_MPPC         Defined for Power Macintosh platforms (no longer supported). 
      _M_MRX000       Defined for MIPS platforms (no longer supported). 
      _M_PPC          Defined for PowerPC platforms (no longer supported). 
      _MFC_VER        Defines the MFC version. Defined as 0x0600 for
                      Microsoft Foundation Class (MFC) Library 6.0 or later.
                      Always defined. 
      _MSC_EXTENSIONS This macro is defined when compiling with the /Ze
                      compiler option (the default).
                      Its value, when defined, is 1. 
      _MSC_VER        Defines the compiler version. Defined as 1200 for
                      Microsoft Visual C++ (MSVC) 6.0 or later. Always defined. 
      _MT             Defined when /MD or /MDd (Multithreaded DLL) or /MT
                      or /MTd (Multithreaded) is specified.  
      _WIN32          Defined for applications for Win32. Always defined.  


  Returns true if test is successful; otherwise returns false.
 */
bool TestPredefinedMacrosC()
{
bool bResult = true;
TsWriteToViewLn(_T("TestPredefinedMacrosC()"));



TsWriteToViewLn(LOG_EOT);

return bResult;
}

/* ////////////////////////////////////////////////////////////////////////// */
/******************************************************************************
 * $Log: 
 *  4    Biblioteka1.3         2004-11-09 18:46:11  Darko Kolakovic implemented
 *       TsWriteToViewLn
 *  3    Biblioteka1.2         2004-10-22 11:46:52  Darko Kolakovic CodeWarrior
 *  2    Biblioteka1.1         2004-09-13 14:28:48  Darko           comments
 *  1    Biblioteka1.0         2004-08-31 12:03:43  Darko           
 * $
 *****************************************************************************/
