/*$Workfile: TestPredefinedMacros.cpp$: implementation file
  $Revision: 4$ $Date: 2004-10-22 12:46:50$
  $Author: Darko Kolakovic$

  Test compiler defined macros.
  Copyright: CommonSoft Inc.
  2004-08-31 Darko Kolakovic
*/

// Group=Examples

  /*Verfy if boolean types are defined. 
    See also <stdbool.h>
   */
#if defined(__MWERKS__)/* Metrowerks CodeWarrior Compiler                    */
  #define _VALIDATE_BOOLEN_TYPE  0
#endif
#include "stdafx.h"
#include "KDbgMacr.h" /*Dump compiler-specific predefined macros*/
#include "KTrace.h"   /*ASSERT_CL macro                         */
#include "KTypedef.h" /*__WFILE__ macro                          */

static const wchar_t *s_pwszFILE = __WFILE__;

extern bool TsWriteToViewLn(LPCTSTR lszText);
bool TestPredefinedMacros();

/*---------------------------------------------------------------------------*/
/*Test predefined macros in C++ compiler. These macros take no arguments and 
  cannot be redefined. Their value (except for __LINE__ and __FILE__) must be 
  constant throughout compilation. Some of the predefined macros listed below 
  are defined with multiple values.
  The compilers should recognize predefined ANSI C macros (see Table 1.1).

      Table 1.1   ANSI-Compliant Predefined Macros

      Macro         Description 
      __cplusplus   Defined for C++ programs only. 
      __DATE__      The compilation date of the current source file. The date
                    is a string literal of the form Mmm dd yyyy. The month name
                    Mmm is the same as for dates generated by the library
                    function asctime() declared in <time.h>.
      __FILE__      The name of the current source file. __FILE__ expands to
                    a string surrounded by double quotation marks.
      __FUNCTION__  Valid only within a function and returns the undecorated
                    name of the enclosing function (as a string).
                    Note: Microsoft specific: __FUNCTION__ is not expanded if 
                    you use /EP or /P compiler options. 
      __LINE__      The line number in the current source file. The line number
                    is a decimal integer constant. It can be altered with a #line
                    directive.
      __TIME__      The most recent compilation time of the current source file.
                    The time is a string literal of the form hh:mm:ss.  
      __TIMESTAMP__ The date and time of the last modification of the current
                    source file, expressed as a string literal in the form 
                    Ddd Mmm Date hh:mm:ss yyyy, where Ddd is the abbreviated
                    day of the week and Date is an integer from 1 to 31. 


  The Microsoft C/C++ implementation provides several more predefined macros
  (see Table 1.2).

      Table 1.2   Some of the Microsoft-Specific Predefined Macros 

      Macro           Description 
      _ATL_VER        Defines the Active Template Library (ATL) version. 
      _CHAR_UNSIGNED  Default char type is unsigned.
                      Defined when /J is specified.  
      __COUNTER__     Increments an integer every time it is used.
      _CPPRTTI        Defined for code compiled with /GR 
                      (Enable Run-Time Type Information). 
      _CPPUNWIND      Defined for code compiled with /GX 
                      (Enable Exception Handling). 
      _DEBUG          Defined when compiling with /LDd, /MDd, /MLd, and /MTd. 
      _DLL            Defined when /MD or /MDd (Multithread DLL) is specified. 
      _M_ALPHA        Defined for DEC ALPHA platforms. It is defined as 1 by
                      the ALPHA compiler, and it is not defined if another
                      compiler is used. 
      _M_IX86         Defined for x86 processors.
      _M_IA64         Defined for 64-bit processors. 
      _M_MPPC         Defined for Power Macintosh platforms (no longer supported). 
      _M_MRX000       Defined for MIPS platforms (no longer supported). 
      _M_PPC          Defined for PowerPC platforms (no longer supported). 
      _MANAGED        Defined to be 1 when /clr is specified. 
      _MFC_VER        Defines the MFC version. Defined as 0x0600 for
                      Microsoft Foundation Class (MFC) Library 6.0 or later.
                      Always defined. 
      _MSC_EXTENSIONS This macro is defined when compiling with the /Ze
                      compiler option (the default).
                      Its value, when defined, is 1. 
      _MSC_VER        Defines the compiler version. Always defined. 
      __MSVC_RUNTIME_CHECKS  Defined when one of the /RTC compiler options
                             is specified. 
      _MT             Defined when /MD or /MDd (Multithreaded DLL) or /MT
                      or /MTd (Multithreaded) is specified.  
      _WIN32          Defined for applications for Win32 and Win64. Always defined.
      _WIN64          Defined for applications for Win64.
      _Wp64           Defined when specifying /Wp64. 


  Returns true if test is successful; otherwise returns false.
 */
bool TestPredefinedMacros()
{
bool bResult = true;
TsWriteToViewLn(_T("TestPredefinedMacros()"));

  #ifdef __STDC_VERSION__
    /*C Standard's version number is a long integer in form: yyyymm where
      yyyy and mm are the year and month of the Standard version.
      This signifies which version of the C Standard the preprocessor
      conforms to.                                                           */
    const long g___STDC_VERSION__ = __STDC_VERSION__;
  #endif

#ifdef __cplusplus
  /*Always defined and set to 199711L.
   */
  const long g__cplusplus_VER = __cplusplus;
#endif

#ifdef _POSIX_
  /*Portable Operating System Interface for Computer Environments (POSIX) 
   */
  #ifdef _POSIX_VERSION
      const long g__POSIX_VERSION = _POSIX_VERSION;
  #endif
#endif




#ifdef __GNUC__  /*GNU C/C++ Compiler                                        */
  #ifdef __GNUC_MINOR__
   /*Current version of GNU compiler. Version number is a long integer in form:
     MMMMmmmm where MMMM is major version and mmmm minor version number      */
    const long g__GNUC_VER = __GNUC__<< 4 + __GNUC_MINOR__;
  #endif

  #ifdef __VERSION__
    /*Macro expands to a string which describes the version major, minor
      number of GNU C and bugfix level in the form "M.m.f"                   */
    const char* g___VERSION__ = __VERSION__;
  #endif
#endif //__GNUC__

#ifdef VXWORKS  /*WindRiver VxWorks Compiler                                 */
  #ifdef VXWORKS_VERSION
    #warning "Target OS is WindRiver VxWorks (ver)."
    /*Note: version.h - VxWorks version information have to be included      */
    const char* g_VXWORKS_VERSION = VXWORKS_VERSION;
  #endif
  #ifdef HOST_TYPE
  /*VxWorks build host OS                                                    */
    const char* g_HOST_TYPE = HOST_TYPE;
  #endif

#endif //VXWORKS

#ifdef _MSC_VER /*Microsoft Visual C/C++ Compiler                            */
   /*Current version of Microsoft compiler.
     The _MSC_VER macro will have one of the following values depending upon
     the particular Microsoft compiler:

        Compiler                             _MSC_VER value

        C Compiler version 6.0                     600
        C/C++ compiler version 7.0                 700
        Visual C++, Windows, version 1.0           800
        Visual C++, 32-bit, version 1.0            800
        Visual C++, Windows, version 1.5           850
        Visual C++, Windows, version 2.0           900
        Visual C++, 32-bit, version 2.x            900
        Visual C++, 32-bit, version 4.0           1000
        Visual C++, 32-bit, version 4.2           1020
        Visual C++, 32-bit, version 5.0           1100
        Visual C++, 32-bit, version 6.0           1200
        Visual C++ .Net 2002, 32-bit, version 7.0 1300
        Visual C++ .Net 2003, 32-bit, version 7.1 1310
     See also: Q65472
    */
    const int g__MSC_VER = _MSC_VER;
  #ifdef _MFC_VER
    #pragma message ("Included Microsoft Fundation Class (MFC) library.")
     /*Current version of Microsoft Fundation Class (MFC) library.
      */
    const int g__MFC_VER = _MFC_VER;
  #endif //_MFC_VER
  #ifdef _ATL_VER
     /*Current version of Active Template Library (ATL).
      */
    const int g__ATL_VER = _ATL_VER;
  #endif //_ATL_VER
  #ifdef _M_IX86
    /*Current version of Intel x86 processor option specified
     */
    const int g__M_IX86 = _M_IX86;
  #endif //_M_IX86
  #ifdef WINVER
    /*Windows Target Version Macros*/
    const WORD g__WINVER = WINVER;
  #endif //WINVER
  #ifdef _WIN32_IE
    /*Supported version of Microsoft Internet Explorer.*/
    const int g__WIN32_IE = _WIN32_IE;
  #endif
#endif //_MSC_VER

#ifdef __DMC__ /*Digital Mars C/C++ Compiler */
    /*Digital Mars C/C++ Compiler version number:
        0x700  v7.0,
        0x720  v7.2,
        0x800  v8.0.
     */
  const long g__DMC__VER = __DMC__;
#endif //__DMC__


TsWriteToViewLn(LOG_EOT);

return bResult;
}

///////////////////////////////////////////////////////////////////////////////
/******************************************************************************
 * $Log: 
 *  4    Biblioteka1.3         2004-10-22 12:46:50  Darko Kolakovic CodeWarrior
 *  3    Biblioteka1.2         2004-10-20 13:23:00  Darko Kolakovic Metrowerks
 *       CodeWarrior
 *  2    Biblioteka1.1         2004-09-13 15:28:46  Darko           comments
 *  1    Biblioteka1.0         2004-08-31 13:03:40  Darko           
 * $
 *****************************************************************************/
