#pragma once

template <class T>
class CProxyDITestAtl7WebEvents : public IConnectionPointImpl<T, &__uuidof( DITestAtl7WebEvents ), CComDynamicUnkArray>
{
	//Warning this class will  be regenerated by the wizard.
public:
};
